controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    skratch_base_controller:
      type: velocity_controllers/JointGroupVelocityController

    kinova_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

skratch_base_controller:
  ros__parameters:
    joints:
      - skratch_1_drive_left_hub_wheel_joint
      - skratch_1_drive_right_hub_wheel_joint
      - skratch_2_drive_left_hub_wheel_joint
      - skratch_2_drive_right_hub_wheel_joint
      - skratch_3_drive_left_hub_wheel_joint
      - skratch_3_drive_right_hub_wheel_joint
      - skratch_4_drive_left_hub_wheel_joint
      - skratch_4_drive_right_hub_wheel_joint
      
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
    
kinova_arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - half_arm_one_joint
      - half_arm_two_joint
      - fore_arm_joint
      - spherical_wrist_one_joint
      - spherical_wrist_two_joint
      - camera_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
